version: "3"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: service_cert
      POSTGRES_USER: service_cert
      POSTGRES_PASSWORD: service_cert
    volumes:
      - service-sert-db-data:/var/lib/postgresql/data
