"""empty message

Revision ID: 50dfc40d7d44
Revises:
Create Date: 2025-01-20 18:57:58.238810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50dfc40d7d44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'service',
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.String(length=512), nullable=True),
        sa.Column('confluence_page_link', sa.String(length=64), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user',
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('nickname', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=64), nullable=False),
        sa.Column('password', sa.String(length=512), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table(
        'release',
        sa.Column('service_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('semantic_version', sa.String(length=32), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['service_id'],
            ['service.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'service_requirement',
        sa.Column('service_id', sa.Uuid(), nullable=False),
        sa.Column('responsible_id', sa.Uuid(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('value', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ['responsible_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['service_id'],
            ['service.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'release_requirement',
        sa.Column('release_id', sa.Uuid(), nullable=False),
        sa.Column('responsible_id', sa.Uuid(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('value', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ['release_id'],
            ['release.id'],
        ),
        sa.ForeignKeyConstraint(
            ['responsible_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_requirement')
    op.drop_table('service_requirement')
    op.drop_table('release')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('service')
    # ### end Alembic commands ###
