"""empty message

Revision ID: 7f327dd0160d
Revises: a2ba4d599621
Create Date: 2025-01-07 13:19:13.725460

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f327dd0160d'
down_revision: Union[str, None] = 'a2ba4d599621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_requirement', sa.Column('responsible_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'release_requirement', 'user', ['responsible_id'], ['id'])
    op.add_column('service_requirement', sa.Column('responsible_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'service_requirement', 'user', ['responsible_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_requirement', type_='foreignkey')
    op.drop_column('service_requirement', 'responsible_id')
    op.drop_constraint(None, 'release_requirement', type_='foreignkey')
    op.drop_column('release_requirement', 'responsible_id')
    # ### end Alembic commands ###
