"""empty message

Revision ID: 80a29566c710
Revises: 90babb5dd626
Create Date: 2025-01-22 17:31:04.613121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80a29566c710'
down_revision: Union[str, None] = '90babb5dd626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_requirement', sa.Column('type', sa.String(length=32), nullable=True))
    op.add_column('service_requirement', sa.Column('type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requirement', 'type')
    op.drop_column('release_requirement', 'type')
    # ### end Alembic commands ###
