"""empty message

Revision ID: 8910d8602463
Revises: 80a29566c710
Create Date: 2025-01-22 18:15:37.600779

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8910d8602463'
down_revision: Union[str, None] = '80a29566c710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'description')
    # ### end Alembic commands ###
