"""empty message

Revision ID: a2ba4d599621
Revises: 9a6d316859aa
Create Date: 2025-01-07 10:37:13.781198

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2ba4d599621'
down_revision: Union[str, None] = '9a6d316859aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_session')
    op.add_column('user', sa.Column('name', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('nickname', sa.String(length=64), nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('first_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False)
    )
    op.add_column(
        'user', sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False)
    )
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'name')
    op.create_table(
        'refresh_session',
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('expired_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('refresh_token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='refresh_session_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='refresh_session_pkey'),
        sa.UniqueConstraint('user_id', name='refresh_session_user_id_key'),
    )
    # ### end Alembic commands ###
