"""empty message

Revision ID: beb360be3916
Revises: 8910d8602463
Create Date: 2025-01-22 19:47:05.129942

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'beb360be3916'
down_revision: Union[str, None] = '8910d8602463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'service_space',
        'homepage_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        'service_space',
        'ext_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'service_space',
        'ext_id',
        existing_type=sa.String(length=64),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        'service_space',
        'homepage_id',
        existing_type=sa.String(length=64),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
